# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: jekyll-org 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "jekyll-org"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["eggcaker"]
  s.date = "2016-10-11"
  s.description = "So you want org-mode support for Jekyll. Write your _posts in org-mode, then add 'gems: [jekyll-org]' to your _config.yml. Thats it!"
  s.email = "eggcaker@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.org"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.org",
    "Rakefile",
    "VERSION",
    "jekyll-org.gemspec",
    "lib/jekyll-org.rb",
    "script/bootstrap",
    "script/cibuild",
    "script/console",
    "script/release",
    "spec/helper.rb",
    "spec/test_jekyll-org.rb"
  ]
  s.homepage = "http://eggcaker.github.io/jekyll-org"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Jekyll converter for org-mode files"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<org-ruby>, [">= 0.9.12"])
      s.add_runtime_dependency(%q<jekyll>, [">= 3.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<org-ruby>, [">= 0.9.12"])
      s.add_dependency(%q<jekyll>, [">= 3.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<org-ruby>, [">= 0.9.12"])
    s.add_dependency(%q<jekyll>, [">= 3.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

