* jekyll-org

** Overview

   This plugin adds [[http://orgmode.org/][Org mode]] support to [[http://jekyllrb.com][Jekyll]] and lets you write posts and pages in Org.

** Requirements

- Jekyll
- org-ruby

** Installation
   1. Install org-ruby
      #+BEGIN_SRC sh
      $ sudo gem install org-ruby
      #+END_SRC
   2. Clone the jekyll-org plugin

      #+BEGIN_SRC sh
      $ git clone http://github.com/eggcaker/jekyll-org.git /path/to/jekyllpath/_plugins/jekyll-org
      #+END_SRC

   If you want use jekyll-org as a submodule, you can:

#+BEGIN_SRC sh
$ cd /path/to/your/jekyll/site/
$ git submodule add http://github.com/eggcaker/jekyll-org.git _plugins/jekyll-org
#+END_SRC

** Usage

   Create a new file with =.org= extesion in =_posts=, and write the post with Org. That is all! Generate your Jekyll site as you usually do.

** Front matter

   Instead of YAML the front matter is configured in the usual Org way, with no lines:

   #+BEGIN_EXAMPLE
   #+TITLE: Jekyll and Org together
   #+LAYOUT: posts
   #+TAGS: jekyll org-mode

   This is a blog post about Jekyll and Org mode.
   #+END_EXAMPLE

** Liquid templating

By default the all content is exported to raw HTML with org-ruby, but you can add =#+liquid: whatevervalue==
in the header.  Then you can use [[http://docs.shopify.com/themes/liquid-documentation/basics][Liquid]] tags.

For example, if your Org file contains

#+BEGIN_EXAMPLE
#+liquid: enabled
#+foo: hello world

{{ page.foo }}

or

{{ site.time | date_to_xmlschema }}

#+END_EXAMPLE

then you will get output like

#+BEGIN_EXAMPLE
<p>hello world</p>
<p>or</p>
<p>2014-07-02T08:20:28+08:00</p>
#+END_EXAMPLE

** Source code highlighting

   Add a source code block as you would in Org, for example Ruby:

  #+BEGIN_EXAMPLE
  #+BEGIN_SRC
   require 'rubygems'
   require 'org-ruby'
   data = IO.read(filename)
   puts Orgmode::Parser.new(data).to_html
  #+END_SRC
  #+END_EXAMPLE

  Then the output will have code highlighting:

  #+BEGIN_SRC ruby
   require 'rubygems'
   require 'org-ruby'
   data = IO.read(filename)
   puts Orgmode::Parser.new(data).to_html
  #+END_SRC

** Author

   eggcaker <eggcaker@gmail.com>

** License

   MIT
